### ISSUE TITLE
Paginator für getAllCourses

### ISSUE THREAD

**Issue by JayReturns** [eerieFoods/SchupfnudelSalat#11]
https://github.com/eerieFoods/SchupfnudelSalat/blob/feature/add-student-controller/sns-server/src/main/java/com/github/eeriefoods/snsserver/course/api/CourseController.java#L35

Hier ein paginator damit nicht zuviel geladen wird. Liste dann standardmäßig alphabetisch sortiert

**Comment by AlexSchmitz222** [comment]
wont fix
